"""
Agent 2 — Bloom's Taxonomy Classifier

Takes questions generated by Agent 1 and assigns a Bloom's level:
- Remember
- Understand
- Apply
- Analyze
- Evaluate
- Create

Design Goals:
✔ Strict structured output (JSON)
✔ Robust against bad LLM formatting
✔ Normalizes inconsistent labels from local models
✔ Easy to plug into next agents (Difficulty, CLO mapping)
"""

from typing import List, Dict
import json
import re


class BloomClassifierAgent:
    def __init__(self, llm):
        self.llm = llm

        # Allowed labels (STRICT)
        self.VALID_LEVELS = [
            "Remember",
            "Understand",
            "Apply",
            "Analyze",
            "Evaluate",
            "Create"
        ]

        # Common mistakes by LLMs → normalize them
        self.NORMALIZATION_MAP = {
            "Application": "Apply",
            "Applying": "Apply",
            "Analysis": "Analyze",
            "Analyzing": "Analyze",
            "Evaluation": "Evaluate",
            "Evaluating": "Evaluate",
            "Creation": "Create",
            "Creating": "Create",
            "Knowledge": "Remember",
            "Comprehension": "Understand",
        }

    # ------------------------------------------------------------------
    # Main function
    # ------------------------------------------------------------------

    def classify(self, questions: List[Dict]) -> List[Dict]:
        """
        Input:
            [
              {"question": "...", "type": "..."},
              ...
            ]

        Output:
            [
              {
                "question": "...",
                "type": "...",
                "blooms_level": "Apply"
              }
            ]
        """

        prompt = f"""
You are an expert in Bloom's Taxonomy for academic exam design.

Classify EACH question into EXACTLY ONE level:

- Remember → Recall facts
- Understand → Explain ideas
- Apply → Use knowledge in a new situation
- Analyze → Break down / compare
- Evaluate → Judge / critique
- Create → Design / generate new ideas

STRICT RULES:
- Output MUST be valid JSON
- Do NOT include explanations
- Do NOT change the question text
- Assign ONLY ONE level per question

Questions:
{questions}

Output format:
[
  {{
    "question": "...",
    "type": "...",
    "blooms_level": "Remember | Understand | Apply | Analyze | Evaluate | Create"
  }}
]
"""

        response = self.llm.invoke(prompt)

        parsed = self._safe_parse(response.content)

        # Normalize labels (CRITICAL for downstream agents)
        normalized = [self._normalize_entry(q) for q in parsed]

        return normalized

    # ------------------------------------------------------------------
    # Robust JSON parsing (handles bad LLM output)
    # ------------------------------------------------------------------

    def _safe_parse(self, text: str) -> List[Dict]:
        """
        Tries multiple strategies to recover JSON from LLM output.
        This is VERY important when using local models.
        """

        # --- Attempt 1: direct JSON parse ---
        try:
            return json.loads(text)
        except:
            pass

        # --- Attempt 2: extract JSON block using regex ---
        try:
            match = re.search(r"\[.*\]", text, re.DOTALL)
            if match:
                return json.loads(match.group(0))
        except:
            pass

        # --- Attempt 3: fallback (return raw text as single entry) ---
        print("[WARN] BloomClassifier: Failed to parse JSON. Returning fallback.")

        return [{
            "question": text.strip(),
            "type": "UNKNOWN",
            "blooms_level": "Understand"  # safe default
        }]

    # ------------------------------------------------------------------
    # Normalize each entry
    # ------------------------------------------------------------------

    def _normalize_entry(self, entry: Dict) -> Dict:
        """
        Ensures:
        - valid bloom label
        - consistent formatting
        """

        level = entry.get("blooms_level", "").strip()

        # Apply normalization mapping
        level = self.NORMALIZATION_MAP.get(level, level)

        # Fix capitalization
        level = level.capitalize()

        # If still invalid → fallback
        if level not in self.VALID_LEVELS:
            print(
                f"[WARN] Invalid Bloom level '{level}' -> defaulting to 'Understand'")
            level = "Understand"

        return {
            "question": entry.get("question", "").strip(),
            "type": entry.get("type", "UNKNOWN"),
            "blooms_level": level
        }
